all::
	../gcode2png cube.gcode
	../gcode2png sphere.gcode
	../gcode2png 3DBenchy.gcode
	../gcode2png --complete=50% --output=3DBenchy-50%.png 3DBenchy.gcode
	../gcode2png PI3_3DBenchy.gcode
	../gcode2png --complete=50% --color=1,0,0 --output=PI3_3DBenchy-50%.png PI3_3DBenchy.gcode

clean::
	rm -f *.png

